name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 */30 * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://www.opengov-muenchen.de/dataset/addaa7d4-40be-4621-846e-c5358cbe3f26/resource/76554a21-34bc-4f62-b609-8af20e0ad9d7/download/places.json | jq . > incidents.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
